from django.urls import URLPattern, path 
from.import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path ("", views.inicio),
    path ("corredor", views.corredor, name="corredor"),
    path ("carreras", views.carreras, name="carreras"),
    path ("teams", views.teams, name="teams"),
    path ("alta_corredor" , views.corredor_formulario),
    path ("alta_carreras" , views.carreras_formulario),
    path ("alta_teams" , views.teams_formulario),
    path ("buscar_corredor", views.buscar_corredor),
    path ("buscar", views.buscar),
    path ("buscar_corredor_apellido", views.buscar_corredor_apellido),
    path ("buscar_apellido", views.buscar_apellido),
    path ("buscar_carreras_nombre", views.buscar_carreras_nombre),
    path ("buscar_carreras", views.buscar_carreras),
    path ("elimina_corredor/<int:id>", views.elimina_corredor, name = "elimina_corredor"),
    path ("editar_corredor/<int:id>" , views.editar_corredor, name="editar_corredor"),
    path ("editar_corredor", views.editar_corredor, name="editar_corredor"),
    path ("elimina_carreras/<int:id>", views.elimina_carreras, name = "elimina_carreras"),
    path ("editar_carreras/<int:id>" , views.editar_carreras, name="editar_carreras"),
    path ("editar_carreras", views.editar_carreras, name="editar_carreras"), 
    path ("elimina_teams/<int:id>", views.elimina_teams, name = "elimina_teams"),
    path ("editar_teams/<int:id>" , views.editar_teams, name="editar_teams"),
    path ("editar_teams", views.editar_teams, name="editar_teams"),
    path ("login", views.login_request, name="login"),
    path ("register", views.register, name="register"),
    path ("logout", LogoutView.as_view(template_name="logout.html") , name="Logout"),
    path ("editar_perfil", views.editar_perfil, name="editar_perfil"),
    path ("nosotros", views.nosotros, name="nosotros"),
    path ("contacto", views.contacto, name="contacto"),
    path ("home", views.home, name='home'),
    path ("noticias", views.noticias, name="noticias"),
    path ("corredoradm", views.corredoradm, name="corredoradm"),
    path ("carrerasadm", views.carrerasadm, name="carrerasadm"),
    path ("teamsadm", views.teamsadm, name="teamsadm"),
    path ("post", views.post, name="post"),
    path ("postadm", views.postadm, name="postadm"),
    path ("alta_post" , views.post_formulario),
    path ("elimina_post/<int:id>", views.elimina_post, name = "elimina_post"),
    path ("perfil", views.perfil, name="perfil"),
]